---
title: "Graphics with ggplot2"
author: "Mary Lardie"
date: "October 22, 2018"
output: html_document
---

#Learning ggplot2

We're learning ggplot2.  It's going to be amazing.
I have no idea what I am doing, but that's ok.

```{r}

# install packages
#install.packages('tidyverse')
library(tidyverse)

#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")
```

Start with California (`ca`) data set

```{r}
head(ca)
View(ca)
```
Plot Cisitation al all CA NP over time

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors))
```

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors, color = park_name))
```

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") +
  theme_bw() + #black and white background
  theme(legend.title = element_blank())
```


```{r}
head(se)
View(se)
```

```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = state)) +
  labs(x = "Year",
       y = "Visitation",
       title = "Southeast National Park Visitation by State") +
  theme_minimal() + #dark background
  theme(legend.title = element_blank()) +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, size = 14, hjust = 1, color = "blue"))
```

```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  facet_wrap(~ state, scales = "free") 
```

```{r}
ggplot(data = se) +
  geom_jitter(aes(x = park_name, y = visitors), alpha = 0.4, width = 0.1) +
  coord_flip()
```

```{r}
ggplot(se) +
  geom_line(aes(x = year, y = visitors, color = park_name)) +
  theme_bw()
```

```{r}
ggplot(data = acadia, aes(x = year, y = visitors)) +
  geom_point() +
  geom_line() +
  geom_smooth() +
  theme_bw()
```

```{r}
install.packages("ggthemes")
library(ggthemes)
```

```{r}
ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity", position = "dodge")
```


```{r}
myplot <- ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity", position = "dodge")

myplot

ggsave (filename = "myplot.png")  #can save at .jpg  or .pfd and so on

```