---
title: "data wrangling"
author: "Mary Lardie"
date: "October 22, 2018"
output: html_document
---

```{r}
library(tidyverse)  # install.packages("tidyverse")
```

## Read Data

This is the gapminder datset.

```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

# inspect the data 
gapminder # looks at all the data
head(gapminder) #give the first 6 rows by default
tail(gapminder) # last 6 observations

head(gapminder, 3)
tail(gapminder, 10)

# summary stats
str(gapminder)
summary(gapminder)

install.packages("skimr")
skimr::skim(gapminder)

names(gapminder) # column names
dim(gapminder) # dimentions
ncol(gapminder) #number of columns
nrow(gapminder) # number of rows

# reverse-engineer dim
c(nrow(gapminder), ncol(gapminder))
```

 ## Dplyr!
 
```{r}
# filter by rows
filter(gapminder, lifeExp < 29)
filter(gapminder, country == "Mexico")
filter(gapminder, country%in% c("Mexico", "Peru", "Brazil"))
filter(gapminder, country == "Mexico", year == 2002)




```

```{r}
#select by columns
select(gapminder, year, lifeExp)
select(gapminder, -continent, -lifeExp)# - will exclude these columns

#use select and filter together
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)
```

## the pipe operator will change your life

```{r}
gapminder %>% head(3)
# is = head(gapminder, 3)

# let's improve this with pipes!
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

#this is the nicer way to say this:

gap_cambodia <- gapminder %>%
  filter (country == "Cambodia") %>% 
  select(-continent, -lifeExp)
```

```{r}
#mutate adds new variables
gapminder %>% 
  mutate(index = 1:nrow(gapminder))

gapminder %>% 
  mutate(planet = "Earth")

gapminder %>% 
  mutate(gdp = pop * gdpPercap)

## Challenge
#Find the max gdp per cap for Egypt and Vietnam, Create new column

gapminder %>% 
  filter (country %in% c("Egypt", "Vietnam")) %>% 
    mutate(gdp = pop * gdpPercap) %>% 
    mutate(max_gdp = max(gdp))

gapminder %>% 
  filter(country %>% c("Egypt", "Vietnam")) %>% 
  mutate(gdp = pop * gdpPercap),
    max_gdp = max(gdp)# there is another way to do this, but I didn't get it.
```


## group_by() groups

```{r}
## with mutate()
gap_grouped <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap,
         max_gdp = max(gdp)) %>% 
  ungroup()
 
##with summarize() or summarise()

gap_summarizd <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  summarise(max_gdp = max(gdp)) %>% 
  ungroup()
```

## `arrange() arranges columns

```{r}
gap_summarizd <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  summarise(max_gdp = max(gdp)) %>% 
  ungroup() %>% 
  arrange(desc(max_gdp))
```

## joining data

```{r}
## read in the data. (same URL as yesterday, with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

## explore

co2 %>% head()
co2 %>% dim()

## create new gapminder variable with on 2007 data
gap_2007 <- gapminder %>% 
  filter(year == 2007)

gap_2007 %>%  dim() 

## left join gap_2007 to co2

lj <- left_join(gap_2007, co2, by = "country")

#another way to write it
lj <- gap_2007 %>% 
  left_join(co2, by = "country")

##right join

rj <- right_join(gap_2007, co2, by = "country")
#same as
lj2 <- left_join(co2, gap_2007, by = "country")
```

```{r}

## read in gapminder data in wide format
gap_wide <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder_wide.csv')
```


## tidyr gather

```{r}
gap_long <- gap_wide %>% 
  gather(key   =obstype_year,
         value =obs_values,
         -continent, -country)
```

## tidyr::separate()

```{r}
gap_long <- gap_wide %>% 
  gather(key   =obstype_year,
         value =obs_values,
         -continent, -country) %>% 
  separate(col = obstype_year,
           into = c("obs_type", "year"),
           sep ="_",
           convert = TRUE)
```

# plot long data

```{r}
canada_df <- gap_long %>% 
  filter(country == "Canada",
         obs_type == "lifeExp")

ggplot(data = canada_df, aes(x= year, y = obs_values)) +
geom_line() +
  theme_bw()
```

##Plot the life exp of all countries in the americas

```{r}
life_df <- gap_long %>% 
  filter(obs_type == "lifeExp",
         continent == "Americas")

ggplot(data = life_df, aes(x= year, y = obs_values, color = country)) +
  geom_line()
```

##plot the mean life exp of each cont over time from 1982 to 2007

```{r}
continents <- gap_long %>% 
  filter(obs_type == "lifeExp",
         year > 1980) %>% 
  group_by(continent, year) %>% 
  summarize(mean_le = mean(obs_values)) %>% 
  ungroup()
                  
ggplot (data = continents, aes(x = year, y = mean_le, color = continent)) +
  geom_line() +
  labs(x = "year",
       y = "Age (years)",
       title = "Mean Life Expectancy") +
  theme_bw()
  
```

##spread




```{r}
gap_normal <- gap_long %>% 
  spread(key = obs_type,
         obs_values)
```

```{r}
gap_wide_new <- gap_long %>% 
  unite(col = var_names, obs_type, year, sep = "_") %>% 
  spread(key = var_names,
         value = obs_values)

  
```


